name: Python Script

on:
  push:
    branches:
      - main  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  
      working-directory: ./GITHUB_WORK

    - name: Run Python script
      run: python Code.py  
