site_name: COINES Documentation
site_url: https://maharavansundaram.github.io/GITHUB_WORK/
repo_url: https://github.com/MaharavanSundaram/GITHUB_WORK
edit_uri: edit/main/doc/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    primary: custom
    accent: custom

  features:
    - header.autohide
    - content.code.copy
    - content.action.edit

extra_css:
  - stylesheets/extra.css      

extra:
  social:
    - icon: fontawesome/solid/file-pdf
      link: /GITHUB_WORK/pdf/coines_documentation.pdf
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/boschMEMS


hide:
  - navigation
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
plugins:
    - search # built-in search must be always activated
    - drawio-exporter:
        # Diagrams are cached to speed up site generation. The default path is
        # drawio-exporter, relative to the documentation directory.
        cache_dir: 'drawio-exporter'
        # Path to the Draw.io executable:
        #   * drawio on Linux
        #   * draw.io on macOS
        #   * or draw.io.exe on Windows
        # We'll look for it on your system's PATH, then default installation
        # paths. If we can't find it we'll warn you.
        drawio_executable: null
        # Additional Draw.io CLI args
        drawio_args: []
        # Output format (see draw.io --help | grep format)
        format: svg
        # Embed format
        #   * The default is to embed via the <img> tag, only rewriting the
        #     value of the src attribute.
        #   * Consider <object type="image/svg+xml" data="{img_src}"></object>
        #     to enable interactive elements (like hyperlinks) in SVGs.
        embed_format: '{img_open}{img_src}{img_close}'
        # Glob pattern for matching source files
        sources: '*.drawio'
    - with-pdf:
        author: Bosch Sensortec
        #
        #cover: false
        #back_cover: true
        # cover_title: TITLE TEXT
        cover_subtitle: ""
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        # render_js: true
        # headless_chrome_path: headless-chromium
        #
        output_path: pdf/coines_documentation.pdf
        # enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        verbose: true