name: Python CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  Runpython:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: pip install -r requirements.txt  

    - name: Run Python script
      run: python Code.py  
