name: LaTeX to HTML Conversion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install TeX Live
      run: |
        sudo apt-get install -y texlive

    - name: Install Pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Compile LaTeX to HTML
      run: |
        pandoc -s -o output.html doc/latex/BST-DHW-AN013-00.tex doc/latex/boschsensortec.sty
      working-directory: ${{ github.workspace }}

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v2
      with:
        name: latex-to-html-artifact
        path: output.html
