name: LaTeX to HTML Conversion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeX Live and Pandoc
        run: |
          sudo apt-get install -y texlive pandoc
        shell: bash

      - name: Convert LaTeX to HTML
        run: |
          pandoc -s -o output.html --include-in-header=boschsensortec.sty doc/latex/BST-DHW-AN013-00.tex
        working-directory: ${{ github.workspace }}

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: latex-to-html-artifact
          path: output.html
