name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MiKTeX
      run: |
        choco install miktex

    - name: Compile LaTeX document
      run: |
        # Change to the directory where your LaTeX document is located
        cd doc/latex

        # Run texify to compile the document (replace 'your-document.tex' with the actual file name)
        texify --pdf --synctex --clean BST-DHW-AN013-00.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: doc/latex/*.pdf
