name: Compile and Store LaTeX document as PDF Artifact

on:
  push:
    branches:
      - main # You can change this to match your branch name
  pull_request:
    branches:
      - main # You can change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TeX Live and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texify

    - name: Compile LaTeX document
      run: |
        # Navigate to the directory containing your TeX files
        cd doc/latex

        # Run pdflatex to compile the TeX document
        texify  BST-DHW-AN013-00.tex

    - name: Store PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: doc/latex/*.pdf
